version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: namespace-manager-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subname-db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - namespace-network

volumes:
  postgres-data:

networks:
  namespace-network:
    driver: bridge
